from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List

import pandas as pd

try:
    from .data_loader import load_all_datasets
    from .predict import predict_from_artifact_dir
    from .preprocessing import make_xy
    from .train import TrainResult, train_all_models
except Exception:
    from data_loader import load_all_datasets
    from predict import predict_from_artifact_dir
    from preprocessing import make_xy
    from train import TrainResult, train_all_models


def _flatten_results(all_results: Dict[str, List[TrainResult]]) -> pd.DataFrame:
    rows: List[Dict[str, Any]] = []
    for model_key, model_results in all_results.items():
        for res in model_results:
            rows.append(
                {
                    "model_key": model_key,
                    "model_name": res.model,
                    "dataset": res.dataset,
                    "accuracy": res.accuracy,
                    "f1_macro": res.f1_macro,
                    "roc_auc": res.roc_auc,
                    "artifact_dir": res.artifact_dir,
                }
            )
    return pd.DataFrame(rows)


def _artifact_smoke_test(metrics_df: pd.DataFrame) -> pd.DataFrame:
    datasets = load_all_datasets()
    checks: List[Dict[str, Any]] = []

    for _, row in metrics_df.iterrows():
        dataset_name = row["dataset"]
        artifact_dir = row["artifact_dir"]
        ok = False
        error = None

        try:
            X_df, _ = make_xy(datasets[dataset_name])
            sample = X_df.head(1)
            pred_out = predict_from_artifact_dir(artifact_dir, sample)
            ok = len(pred_out["pred_labels"]) == 1
        except Exception as exc:
            error = str(exc)

        checks.append(
            {
                "model_key": row["model_key"],
                "dataset": dataset_name,
                "artifact_dir": artifact_dir,
                "predict_ok": ok,
                "error": error,
            }
        )

    return pd.DataFrame(checks)


def run_mlops_pipeline(
    dataset_name: str | None = None,
    reports_dir: str = "reports/mlops",
    artifacts_dir: str = "data/models",
    verbose: bool = True,
) -> Dict[str, Any]:
    """
    Run MLOps pipeline:
    1) Train all models
    2) Save model artifacts
    3) Save metrics report
    4) Smoke-test prediction from saved artifacts
    """
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    report_path = Path(reports_dir)
    report_path.mkdir(parents=True, exist_ok=True)

    all_results = train_all_models(
        dataset_name=dataset_name,
        save_artifacts=True,
        artifacts_base_dir=artifacts_dir,
        skip_failed_models=True,
        verbose=verbose,
    )

    metrics_df = _flatten_results(all_results)
    if metrics_df.empty:
        raise RuntimeError("No model results generated by pipeline.")

    metrics_df = metrics_df.sort_values(["dataset", "f1_macro"], ascending=[True, False])
    metrics_csv = report_path / f"metrics_{timestamp}.csv"
    metrics_latest_csv = report_path / "metrics_latest.csv"
    metrics_df.to_csv(metrics_csv, index=False)
    metrics_df.to_csv(metrics_latest_csv, index=False)

    best_df = metrics_df.groupby("dataset", as_index=False).first()
    best_json = report_path / f"best_models_{timestamp}.json"
    best_latest_json = report_path / "best_models_latest.json"
    best_df.to_json(best_json, orient="records", indent=2)
    best_df.to_json(best_latest_json, orient="records", indent=2)

    checks_df = _artifact_smoke_test(metrics_df)
    checks_csv = report_path / f"artifact_checks_{timestamp}.csv"
    checks_latest_csv = report_path / "artifact_checks_latest.csv"
    checks_df.to_csv(checks_csv, index=False)
    checks_df.to_csv(checks_latest_csv, index=False)

    if verbose:
        print("\nPipeline completed.")
        print(f"- Metrics: {metrics_csv}")
        print(f"- Best models: {best_json}")
        print(f"- Artifact checks: {checks_csv}")

    return {
        "all_results": all_results,
        "metrics_df": metrics_df,
        "best_df": best_df,
        "checks_df": checks_df,
        "paths": {
            "metrics_csv": str(metrics_csv),
            "metrics_latest_csv": str(metrics_latest_csv),
            "best_json": str(best_json),
            "best_latest_json": str(best_latest_json),
            "checks_csv": str(checks_csv),
            "checks_latest_csv": str(checks_latest_csv),
        },
    }


if __name__ == "__main__":
    run_mlops_pipeline()
